# Generated by Django 2.0.5 on 2020-05-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='gamePhoto', verbose_name='Фото')),
                ('video', models.ImageField(blank=True, upload_to='gameVideo', verbose_name='Видео')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('android', models.BooleanField(default=False, verbose_name='Android')),
                ('ios', models.BooleanField(default=False, verbose_name='IOS')),
                ('windows', models.BooleanField(default=False, verbose_name='Windows')),
                ('psp', models.BooleanField(default=False, verbose_name='PSP')),
                ('xbox', models.BooleanField(default=False, verbose_name='X-Box')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('language', models.BooleanField(default=False, verbose_name='Русский язык')),
                ('paidContent', models.BooleanField(default=False, verbose_name='Платный контент')),
                ('advertising', models.BooleanField(default=False, verbose_name='Реклама')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Игру',
                'verbose_name_plural': 'Игры',
                'ordering': ['added', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=548, verbose_name='Коментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен комментария')),
                ('photo', models.ImageField(blank=True, upload_to='gameCommentPhoto', verbose_name='Фото комментария')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['game'],
            },
        ),
        migrations.CreateModel(
            name='GamePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gamePhoto', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['game'],
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Game', to_field='name', verbose_name='Название')),
            ],
        ),
    ]
