# Generated by Django 2.0.5 on 2020-05-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользаватель'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Game', to_field='name', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='gamephoto',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Game', to_field='name', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Game', to_field='name', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Genre', to_field='name', verbose_name='Жанр'),
        ),
    ]
